### ISSUE TITLE
Where to write the Prompts

### ISSUE THREAD

**Issue by Tobe2d** [juanigsrz/sd-fractal-zoom#1]
I Installed it using the webui and after restart I went to fractal zoom tab and I see this:
![image](https://user-images.githubusercontent.com/4099839/219879510-f1212e1e-5f0b-4806-a474-8d2596a3cdad.png)

Where to write the Prompts?

**Comment by juanigsrz** [comment]
Hello Tobe2d, I just started this project around 2 days ago and there is no fully working extension yet, I haven't even done a release even though my local version is quite close. Not sure how you found this project but I'll make sure to finish and publish a working version in the next few days.

Here is an example of the current version: https://imgur.com/a/edj2RYs

I need to fix the resolution degradation before I make a working release.

**Comment by Tobe2d** [comment]
@juanigsrz the example looks Amazing!!!!

Cant wait ;-)

**Comment by Tobe2d** [comment]
Any news on this?
